In [2]:
# import all neccesary packages and library
# For data manipualtion where neccesary
import pandas as pd
import numpy as np

# For data visualization where neccesary
import seaborn as sns
import matplotlib.pyplot as plt

# For preprocessing 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Classifier algorithms for data training (All from scikit-learn)
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

# For evaluating the model
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix,classification_report

# For saving the model
import pickle

#Define random state
random_state = 234

# To handle warnings
import warnings
warnings.filterwarnings("ignore")



KeyboardInterrupt



1.4.2


In [112]:
# Load all the datasets
train = pd.read_csv("Training.csv")
symptoms = pd.read_csv("symtoms_df.csv")
desc = pd.read_csv("description.csv")
medic = pd.read_csv("medications.csv")
prec = pd.read_csv("precautions_df.csv")
diet = pd.read_csv("diets.csv")
severity = pd.read_csv("Symptom-severity.csv")
workouts = pd.read_csv("workout_df.csv")

In [3]:
# Taking a snapshot of the dataset
train.head(2)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  

[2 rows x 133 columns]

In [4]:
# checking th dimension of the dataframe
train.shape

(4920, 133)

In [5]:
# Checking if there are missing values
train.isna().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [6]:
# Checking for duplicates
train.duplicated().sum()

4616

In [7]:
# Viewing the columns in list
print(list(train.columns))

['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_during_bow

In [8]:
# Viewing the target variable
train["prognosis"]

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [9]:
train["prognosis"].nunique()

41

In [10]:
train["prognosis"].value_counts()

prognosis
Fungal infection                           120
Hepatitis C                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Hepatitis D                                120
Hepatitis B                                120
All

In [11]:
# filter for a particular prognosis
Acne = train[train["prognosis"]=="Acne"]

In [12]:
Acne.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
370        0          1                     0                    0          0   
371        0          1                     0                    0          0   
372        0          0                     0                    0          0   
373        0          1                     0                    0          0   
374        0          1                     0                    0          0   

     chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
370       0           0             0        0                 0  ...   
371       0           0             0        0                 0  ...   
372       0           0             0        0                 0  ...   
373       0           0             0        0                 0  ...   
374       0           0             0        0                 0  ...   

     blackheads  scurring  skin_peeling  silver_like_dusting  \
370           1         1             0                    0   
371           1         1             0                    0   
372           1         1             0                    0   
373           1         1             0                    0   
374           0         1             0                    0   

     small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
370                     0                   0        0                     0   
371                     0                   0        0                     0   
372                     0                   0        0                     0   
373                     0                   0        0                     0   
374                     0                   0        0                     0   

     yellow_crust_ooze  prognosis  
370                  0       Acne  
371                  0       Acne  
372                  0       Acne  
373                  0       Acne  
374                  0       Acne  

[5 rows x 133 columns]

In [13]:
Acne.duplicated().sum()

115

In [14]:
Acne.shape

(120, 133)

NOTEd: There seem to be duplicates in the dataset, but all of the duplicates have exact numbers. Dropping them will leave with just 41 rows of data which might not be enough for my model building.
Hence, I will leave the dataset the way it is. Since, its a medical data, tempering with it might make our model behave in an unintended manner.

In [16]:
## Preprocess the data and build the model
### Do the first splitting into features and target variable

X = train.drop("prognosis", axis = 1) # features
y = train["prognosis"] # target variable

In [17]:
X.shape[1]  # We have 132 features

132

In [18]:
y.shape # we have just one target

(4920,)

In [19]:
print(y)

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object


In [20]:
print(y)
## Lets do further preprocessing by encoding our target variable into its numeric representation to ensure a seemless classification
label_encoder = LabelEncoder() # initialize encoder
Y = label_encoder.fit_transform(y)
print(Y)

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object
[15 15 15 ... 38 35 27]


In [21]:
# LEts see if our target variable has been successfully been encoded
print(Y)

[15 15 15 ... 38 35 27]


In [22]:
Y.shape

(4920,)

In [23]:
### Do the second splitting for training and testing the model.
##### THe split is in thw ratio of 70:30, 70% to train the algorithm and 30% to test the model
X_train,X_test,y_train,y_test = train_test_split(X,Y, test_size = 0.3, random_state = random_state)

In [24]:
X_train.shape

(3444, 132)

In [25]:
y_train.shape

(3444,)

In [26]:
X_test.shape

(1476, 132)

In [27]:
y_test.shape

(1476,)

In [28]:
## LEts build our model 
#1. Algorithm selection inside a dictionary
## I will be using clusters of classifiers to see the best performing  model
# SVC, Ensembles, Kneighbors, Naive_bayes

training_algorithms = {
    "SVC":SVC(kernel= "linear"),
    "RandomForest": RandomForestClassifier(n_estimators = 100, random_state =random_state),
    "GradientBoosting": GradientBoostingClassifier(n_estimators = 100, random_state =random_state),
    "KNeigbors":KNeighborsClassifier(n_neighbors = 5),
    "MultinormialNB": MultinomialNB()}

In [29]:
# Loop all the algorithms together
for algorithm_names, training_algorithm in training_algorithms.items():
    print(algorithm_names,":",training_algorithm)

SVC : SVC(kernel='linear')
RandomForest : RandomForestClassifier(random_state=234)
GradientBoosting : GradientBoostingClassifier(random_state=234)
KNeigbors : KNeighborsClassifier()
MultinormialNB : MultinomialNB()


In [30]:
# LEts train our algorithm with our data to get out model
for algorithm_names, training_algorithm in training_algorithms.items():
    models = training_algorithm.fit(X_train,y_train)#.....train
    predictions = models.predict(X_test) #................predict
    accuracy = accuracy_score(y_test,predictions) #......Test
    cm = confusion_matrix(y_test,predictions)#.Evaluate

    #print results
    print(f"{algorithm_names} accuracy: {accuracy}")
    print(f"{algorithm_names} confusion_matrix: ")
    print(np.array2string(cm,separator =','))
    print("_______________________________________________")
    

SVC accuracy: 1.0
SVC confusion_matrix: 
[[35, 0, 0,..., 0, 0, 0],
 [ 0,33, 0,..., 0, 0, 0],
 [ 0, 0,35,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,40, 0, 0],
 [ 0, 0, 0,..., 0,36, 0],
 [ 0, 0, 0,..., 0, 0,30]]
_______________________________________________
RandomForest accuracy: 1.0
RandomForest confusion_matrix: 
[[35, 0, 0,..., 0, 0, 0],
 [ 0,33, 0,..., 0, 0, 0],
 [ 0, 0,35,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,40, 0, 0],
 [ 0, 0, 0,..., 0,36, 0],
 [ 0, 0, 0,..., 0, 0,30]]
_______________________________________________
GradientBoosting accuracy: 1.0
GradientBoosting confusion_matrix: 
[[35, 0, 0,..., 0, 0, 0],
 [ 0,33, 0,..., 0, 0, 0],
 [ 0, 0,35,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,40, 0, 0],
 [ 0, 0, 0,..., 0,36, 0],
 [ 0, 0, 0,..., 0, 0,30]]
_______________________________________________
KNeigbors accuracy: 1.0
KNeigbors confusion_matrix: 
[[35, 0, 0,..., 0, 0, 0],
 [ 0,33, 0,..., 0, 0, 0],
 [ 0, 0,35,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,40, 0, 0],
 [ 0, 0, 0,..., 0,36, 0],
 [ 0, 0, 0,...

**RESULT INTERPRETATION**

From the result we seem to have a perfect model with 100% accuracy. All of the models have thesame result. But I will work wih the fastest for the automation.

**CHOOSING A MODEL**

MultinomialNB
I will be using Naive_Bayes for my prediction, the reasons are listed below:

Speed:
Training: Very fast, as it computes simple probabilities based on the training data.
Prediction: Very fast, as it involves basic probability calculations.
Suitability: Ideal for text data or categorical features, especially when features are independent.

In [33]:
# TRAINING A SINGLE MODEL WITH NAIVE_BAYES

# Define and train the model
algorithm = MultinomialNB()
model = algorithm.fit(X_train, y_train)
predicted_y = model.predict(X_test)


# Calculate metrics
accuracy = accuracy_score(y_test, predicted_y)
precision = precision_score(y_test, predicted_y, average='weighted')  
recall = recall_score(y_test, predicted_y, average='weighted')  # Sensitivity
f1 = f1_score(y_test, predicted_y, average='weighted')

# Confusion matrix for multi-class classification
conf_matrix = confusion_matrix(y_test, predicted_y)

# Print results
print("Predicted labels: ", predicted_y)
print("True labels: ", y_test)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision (Weighted): {precision:.2f}")
print(f"Recall (Weighted): {recall:.2f}")
print(f"F1-Score (Weighted): {f1:.2f}")
print("\nConfusion Matrix:")
print(conf_matrix)

# Generate and print a full classification report
print("\nClassification Report:")
print(classification_report(y_test, predicted_y))

Predicted labels:  [17 24 31 ...  9  7 40]
True labels:  [17 24 31 ...  9  7 40]
Accuracy: 100.00%
Precision (Weighted): 1.00
Recall (Weighted): 1.00
F1-Score (Weighted): 1.00

Confusion Matrix:
[[35  0  0 ...  0  0  0]
 [ 0 33  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 40  0  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  0 30]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       1.00      1.00      1.00        33
           2       1.00      1.00      1.00        35
           3       1.00      1.00      1.00        35
           4       1.00      1.00      1.00        34
           5       1.00      1.00      1.00        36
           6       1.00      1.00      1.00        35
           7       1.00      1.00      1.00        45
           8       1.00      1.00      1.00        34
           9       1.00      1.00      1.00        32
          10       1.00      1

**SAVE THE MODEL, RELOAD AND TEST THE MODEL**

In [35]:
# using the pickel library to save the model
with open("naive_bayes_model.pkl","wb") as file:
    pickle.dump(model, file)
print("model saved sucessfully, please check your folder...")


model saved sucessfully....


**....load in model...**

In [37]:
# load in the model and giving it a variable name "my_model"
my_model = pickle.load(open("naive_bayes_model.pkl","rb"))

In [38]:
# lets use the model for prediction

# first test
print("Predicted label: ", my_model.predict(X_test.iloc[0].values.reshape(1,-1)))
print("Actual label ",y_test[0])

Predicted label:  [17]
Actual label  17


In [39]:
# second test
print("Predicted label: ", my_model.predict(X_test.iloc[10].values.reshape(1,-1)))
print("Actual label ",y_test[10])

Predicted label:  [26]
Actual label  26


In [40]:
# third test
print("Predicted label: ", my_model.predict(X_test.iloc[21].values.reshape(1,-1)))
print("Actual label ",y_test[21])

Predicted label:  [29]
Actual label  29


**BUILD THE RECOMMENDATION SYSTEM LOGIC**

In [42]:
## Bringing down the rest of my dataset
#symptoms.head(2)


In [43]:
train.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [44]:
# Dictionary comprehension
# Convert the column names of the features to  to a dictionary usinng index as values while the column name becomes the key
symptoms_dict = {column: index + 0 for index, column in enumerate(X.columns)}

print(symptoms_dict)


{'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and

In [45]:
# Dictioanry comprehension...
# Create a dictionary  for the target variable using  both the encoded and the target variable and keeping the uniques values for the dictioanry
disease_dict = {encoded: original for encoded, original in zip(Y, label_encoder.inverse_transform(Y))}

print("disease:", disease_dict)

disease: {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}


In [46]:
# Creating a prediction function
diseases_list = list(y)

In [47]:
diseases_list

['Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Fungal infection',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'Allergy',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'GERD',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Chronic cholestasis',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Drug Reaction',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer diseae',
 'Peptic ulcer d

In [161]:
# Recommender Engine
def predict_ailment(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        input_vector[symptoms_dict[item]] = 1
    return diseases_list[my_model.predict([input_vector])[0]]

In [163]:
# Added functionalties
def include_features(predicted_disease):
    description = desc[desc["Disease"] ==predicted_disease]["Description"]
    description = "".join([dr for dr in description])
    
    precaution = prec[prec["Disease"]==predicted_disease][["Precaution_1","Precaution_2","Precaution_3","Precaution_4"]]
    precaution = [col for col in precaution.values]

    medication = medic[medic["Disease"]== predicted_disease]["Medication"]
    medication = [med for med in medication.values]

    diets = diet[diet["Disease"] == predicted_disease]["Diet"]
    diets = [di for di in diets.values]

    workout = workouts[workouts["disease"] == predicted_disease]["workout"]
    workout = [wk for wk in workout.values]
    
    return description,precaution,medication,diets,workout

In [165]:
# # Repert format...

# def generate_report(predicted_disease, description,precaution,medication,diets,workout):
#     print("___________________________________________________")
#     print("           PREDICTION AND RECOMMENDATION REPORT    ")
#     print("___________________________________________________")

#     print("_________________Predicted Disease_________________")
#     print(predicted_disease)

#     print("_________________Disease Description_______________")
#     print(description)
#     print("_________________Precautions_______________________")
#     i = 1
#     for p in precaution[0]:
#         print(i,":", p)
#         i = i + 1
#     print("_________________Medications_______________________")
#     i = 1
#     for m in medication:
#         print(m)
#         i = i + 1

#     print("_________________Diets_____________________________")
#     i = 1
#     for d in diets:
#         print(d)
#         i = i + 1

#     print("_________________Workouts__________________________")
#     i = 1
#     for w in workout:
#         print(i,":", w)
#         i = i + 1
#     print("+++++++++++++++| Health is Wealth |+++++++++++++++++")

In [183]:
from tabulate import tabulate

def generate_formated_report(predicted_disease, description, precaution, medication, diets, workout):
   
    # Prepare rows for the report
    rows = [
        ["\033[1mPredicted Disease\033[0m", predicted_disease],
        ["\033[1mDescription\033[0m", description],
        ["\033[1mPrecautions\033[0m", "\n".join(f"{i+1}. {p}" for i, p in enumerate(precaution[0]))],
        ["\033[1mMedications\033[0m", "\n".join(f" {m}" for m in medication)],
        ["\033[1mDiets\033[0m", "\n".join(f" {d}" for d in diets)],
        ["\033[1mWorkouts\033[0m", "\n".join(f"{i+1}. {w}" for i, w in enumerate(workout))]
    ]

    # Generate the table with `grid` for straight vertical and horizontal lines
    table = tabulate(
        rows,
        headers=["\033[1mPredictions\033[0m", "\033[1mDetails\033[0m"],
        tablefmt="grid"
    )

    # Calculate the length of the table and the separator line length
    table_length = len(table.splitlines()[0])  # Length of the first row in the table

    # Create the header and footer lines with the same length as the table
    header_footer_line = "━" * table_length

    # Print the styled report
    print(header_footer_line)
    print("{:^70}".format("\033[1mPREDICTION AND RECOMMENDATION REPORT\033[0m"))
    print(header_footer_line)
    print(table)
    print(header_footer_line)
    print("{:^70}".format("\033[1mHealth is Wealth!\033[0m"))
    print(header_footer_line)

In [185]:
# # prediction test1 ...
symptoms = input("Enter your symptoms....")
user_symptoms = [s.strip() for s in symptoms.split(',')]
user_symptoms = [sym.strip("[]") for sym in user_symptoms]
predicted_disease = predict_ailment(user_symptoms)
description,precaution,medication,diets,workout=include_features(predicted_disease)
#generate_report(predicted_disease, description,precaution,medication,diets,workout)
generate_formated_report(predicted_disease, description, precaution, medication, diets, workout)

Enter your symptoms.... shivering,chills,joint_pain,stomach_pain,acidity


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
             PREDICTION AND RECOMMENDATION REPORT             
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
+-------------------+------------------------------------------------------------------------------------+
| Predictions       | Details                                                                            |
+===================+====================================================================================+
| Predicted Disease | Fungal infection                                                                   |
+-------------------+------------------------------------------------------------------------------------+
| Description       | Fungal infection is a common skin condition caused by fungi.                       |
+-------------------+------------------------------------------------------------

In [ ]:
# # Handling Exceptions..........

# def predict_ailment(patient_symptoms):
   
#     input_vector = np.zeros(len(symptoms_dict))
#     for symptom in patient_symptoms:
#         if symptom in symptoms_dict:
#             input_vector[symptoms_dict[symptom]] = 1
#         else:
#             raise ValueError(f"Invalid symptom: {symptom}. Please enter valid symptoms from the list.")
#     return model.predict([input_vector])[0]

# def preprocess_input(user_input):
    
#     formatted_symptoms = [
#         s.strip().lower().replace(" ", "_").strip("[]") for s in user_input.split(',')
#     ]
#     return formatted_symptoms

# # Prediction loop
# while True:
#     try:
#         # Input symptoms from the user
#         symptoms = input("Enter your symptoms (comma-separated): ")
        
#         # Preprocess user input
#         user_symptoms = preprocess_input(symptoms)
        
#         # Predict the ailment
#         predicted_disease = predict_ailment(user_symptoms)
#         print(f"The predicted disease is: {predicted_disease}")
#         break  # Exit the loop on successful prediction

#     except ValueError as e:
#         # Handle invalid input and prompt the user to try again
#         print(e)
#         print("Please try again.")


In [ ]:
#medic.head(2)

In [ ]:
#prec.head(2)

In [ ]:
#diet.head(2)

In [ ]:
#severity.head(2)